hw02 complete
Sjuanita/hm_01 pull request #2
Opened 2023-06-13 15:51 UTC by Sjuanita

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-14 12:51 UTC, ityulkanov requested changes
Аппрув, но надо файл golangci вернуть, он для линтеров нужен. Остальное больше пожелания чем необходимые изменения. Ну и не уверен что такое решение годится для задачи со *.

2023-06-14 12:51 UTC, ityulkanov commented on .golangci.yml
Надо бы вернуть)

2023-06-14 12:51 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +		case val >= 48 && val <= 57:
```suggestion
		case val >= '0' && val <= '9':
```

2023-06-14 12:51 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
```suggestion
const zeroValue = -1
```

2023-06-14 12:51 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +				num = -1
```suggestion
				num = zeroValue
```

2023-06-14 12:51 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +			} else if num != -1 {
```suggestion
			} else if num != zeroValue {
```

2023-06-14 13:03 UTC, Sjuanita commented on hw02_unpack_string/unpack.go
> +		case val >= 48 && val <= 57:
Тут привычка, на си писал именно по аски коду)

2023-06-14 13:12 UTC, engineer-go approved these changes

2023-06-14 16:19 UTC, merged

2023-06-29 11:41 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +		case val >= 48 && val <= 57:
да можно и так, но по мне так лучше заранее стараться снижать cognitive load для тех кто будет поддерживать ваш код в будущем.